-- =============================================================
-- T3Composer — 사용 이력 화면 메뉴 등록
-- =============================================================
-- Version : v26.0.0 (Stage 5)
-- Created : 2026-04-22
-- 내용   : UI_UT_COMPOSER_HISTORY 메뉴 + 다국어 라벨
-- =============================================================

-- 재실행 대비 기존 항목 제거
DELETE FROM TB_AD_MENU_BADGE
    WHERE MENU_ID IN (SELECT ID FROM TB_AD_MENU WHERE MENU_CD = 'UI_UT_COMPOSER_HISTORY');

DELETE FROM TB_AD_MENU_BOOKMARK
    WHERE MENU_ID IN (SELECT ID FROM TB_AD_MENU WHERE MENU_CD = 'UI_UT_COMPOSER_HISTORY');

DELETE FROM TB_AD_MANUAL
    WHERE MENU_CD = 'UI_UT_COMPOSER_HISTORY';

DELETE FROM TB_AD_MENU
    WHERE MENU_CD = 'UI_UT_COMPOSER_HISTORY';


-- UI_UT_COMPOSER_HISTORY — 사용 이력 화면
INSERT INTO TB_AD_MENU (ID, PARENT_ID, MENU_CD, MENU_PATH, MENU_SEQ, USE_YN, CREATE_BY, CREATE_DTTM, MENU_FILE_PATH)
SELECT
    REPLACE(NEWID(), '-', ''),
    ID,
    N'UI_UT_COMPOSER_HISTORY',
    N'/util/t3composerhistory',
    2,
    'Y',
    N'system',
    CONVERT(DATE, '1970-01-01 00:00:00'),
    N'/util/T3ComposerHistory'
FROM TB_AD_MENU
WHERE MENU_CD = 'MENU_UT_T3COMPOSER';


-- 다국어 라벨
DELETE FROM TB_AD_LANG_PACK WHERE LANG_KEY = 'UI_UT_COMPOSER_HISTORY';

INSERT INTO TB_AD_LANG_PACK (LANG_CD, LANG_KEY, LANG_VALUE) VALUES ('ko', 'UI_UT_COMPOSER_HISTORY', N'사용 이력');
INSERT INTO TB_AD_LANG_PACK (LANG_CD, LANG_KEY, LANG_VALUE) VALUES ('en', 'UI_UT_COMPOSER_HISTORY', N'History');
INSERT INTO TB_AD_LANG_PACK (LANG_CD, LANG_KEY, LANG_VALUE) VALUES ('ja', 'UI_UT_COMPOSER_HISTORY', N'履歴');
INSERT INTO TB_AD_LANG_PACK (LANG_CD, LANG_KEY, LANG_VALUE) VALUES ('zh', 'UI_UT_COMPOSER_HISTORY', N'使用历史');

-- 결과 확인
SELECT MENU_CD, MENU_PATH, MENU_FILE_PATH, MENU_SEQ
FROM   TB_AD_MENU
WHERE  MENU_CD IN ('MENU_UT_T3COMPOSER', 'UI_UT_COMPOSER', 'UI_UT_COMPOSER_HISTORY')
ORDER  BY MENU_SEQ;
