#!/usr/bin/env bash
# =============================================================================
# T-SQL → PostgreSQL 자동 변환 — Composer init SQL 전용
# =============================================================================
# 입력: docker/db/init/*.sql  (T-SQL)
# 출력: docker/db/init-pg/*.sql (PG)
#
# 변환 후 PG 에 직접 적용하면서 실패하는 곳만 수동으로 다시 손봄. 본 스크립트는
# 기계적으로 90% 이상 변환하는 보조 도구 — 100% 자동을 목표로 하지 않음.
# =============================================================================
set -e

SRC_DIR="$(dirname "$0")/../init"
DST_DIR="$(dirname "$0")"

echo "[convert] src=$SRC_DIR dst=$DST_DIR"

for f in "$SRC_DIR"/*.sql; do
    name="$(basename "$f")"
    # 01_create_database.sql 은 PG 컨테이너 환경변수가 DB 생성을 담당 — 별도 SQL 불필요
    if [ "$name" = "01_create_database.sql" ]; then
        echo "[convert] skip $name (PG container env vars handle this)"
        continue
    fi
    # 11_composer_layout_rollback.sql 은 cleanup 용 (init 불필요).
    # T-SQL IF/BEGIN/END + DECLARE @VAR + CAST + AS NVARCHAR 등 자동 변환 어려움.
    # 필요 시 수동 PL/pgSQL DO block 으로 변환할 것.
    if [ "$name" = "11_composer_layout_rollback.sql" ]; then
        echo "[convert] skip $name (rollback cleanup — init 불필요, 수동 변환 대상)"
        continue
    fi

    out="$DST_DIR/$name"
    echo "[convert] $name -> $out"

    # 변환 파이프라인 — 순서가 중요
    sed -E \
        -e 's/\bNVARCHAR\(MAX\)/text/Ig' \
        -e 's/\bVARCHAR\(MAX\)/text/Ig' \
        -e 's/\bVARBINARY\(MAX\)/bytea/Ig' \
        -e 's/\bVARBINARY\([0-9]+\)/bytea/Ig' \
        -e 's/\bBINARY\([0-9]+\)/bytea/Ig' \
        -e 's/\bIMAGE\b/bytea/Ig' \
        -e 's/\bNVARCHAR\(([0-9]+)\)/varchar(\1)/Ig' \
        -e 's/\bNCHAR\(([0-9]+)\)/char(\1)/Ig' \
        -e 's/\bCHAR\(\s*(9|10|13)\s*\)/chr(\1)/g' \
        -e 's/\bDATETIME2/timestamp/Ig' \
        -e 's/\bDATETIME\b/timestamp/Ig' \
        -e 's/\bBIT\b/boolean/Ig' \
        -e 's/\bGETDATE\(\)/now()/Ig' \
        -e 's/\bNEWID\(\)/gen_random_uuid()::text/Ig' \
        -e "s/\bN'/'/g" \
        -e 's/^GO\s*$//Ig' \
        -e 's/^\s*USE\s+[A-Za-z_][A-Za-z0-9_]*\s*;?\s*$//Ig' \
        -e 's/^\s*SET\s+NOCOUNT\s+(ON|OFF)\s*;?\s*$//Ig' \
        -e 's/^\s*SET\s+(ANSI_NULLS|QUOTED_IDENTIFIER|XACT_ABORT|ARITHABORT|CONCAT_NULL_YIELDS_NULL)\s+(ON|OFF)\s*;?\s*$//Ig' \
        -e 's/\bT3SMARTSCM\.dbo\./dbo./Ig' \
        -e 's/\bT3SMARTSCM\.\.//Ig' \
        -e 's/\bT3SMARTSCM\.//Ig' \
        -e 's/\bIDENTITY\(([0-9]+),\s*[0-9]+\)/GENERATED BY DEFAULT AS IDENTITY/Ig' \
        -e 's/\bNONCLUSTERED\s+INDEX/INDEX/Ig' \
        -e 's/\bCLUSTERED\s+INDEX/INDEX/Ig' \
        -e 's/\bSCOPE_IDENTITY\s*\(\s*\)/lastval()/Ig' \
        -e 's/\bSYSDATETIME\s*\(\s*\)/now()/Ig' \
        -e 's/\bSYSUTCDATETIME\s*\(\s*\)/now() at time zone '\''UTC'\''/Ig' \
        -e 's/\bCONVERT\s*\(\s*DATE\s*,\s*'\''([^'\'']+)'\''\s*\)/'\''\1'\''::date/Ig' \
        -e 's/\bCONVERT\s*\(\s*VARCHAR\([^)]*\)\s*,\s*([^,)]+)\)/(\1)::text/Ig' \
        -e 's/\bISNULL\s*\(/COALESCE(/Ig' \
        -e 's/\bCHARINDEX\s*\(/strpos(/Ig' \
        -e 's/\bLEN\s*\(/char_length(/Ig' \
        -e 's/\bGETUTCDATE\(\)/(now() at time zone '\''UTC'\'')/Ig' \
        -e 's/\bDATEADD\s*\(\s*(day|DAY)\s*,\s*([^,]+),\s*([^)]+)\)/((\3) + (\2) * interval '\''1 day'\'')/Ig' \
        -e 's/\bDATEDIFF\s*\(\s*(day|DAY)\s*,\s*([^,]+),\s*([^)]+)\)/(((\3)::date - (\2)::date))/Ig' \
        -e 's/PRINT\s+'\''([^'\'']*)'\''\s*;?/\\echo '\''\1'\''/Ig' \
        "$f" > "$out"
done

echo "[convert] done. Now: review $DST_DIR/*.sql for IF OBJECT_ID / BEGIN TRY / MERGE patterns."
